spring:
  application:
    name: SportCenter
  datasource:
    url: jdbc:mysql://localhost:3306/sport_center
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 9000
